name: CI Pipeline

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Delete Old Docker image
      run: docker rmi api:latest 2>/dev/null
    - name: Build api docker image
      run: docker build . --file api/Dockerfile --tag api:latest
    - name: List all docker images
      run: docker image ls 
