name: CI Pipeline

on:
  push:
    branches: 
    - master

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Login to Dockerhub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD 
    - name: Build Docker Image
      working-directory: ./api
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: docker build . -f Dockerfile -t $DOCKERHUB_USERNAME/gameshop-backend:latest
    - name: Push image to Dockerhub
      env: 
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: docker push $DOCKERHUB_USERNAME/gameshop-backend:tagname
