name: CI Pipeline

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build api docker image
      working-directory: ./api
      run: docker build . --file Dockerfile --tag api:latest
    - name: Docker login
      run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gameshop-app
