name: CI Pipeline

on:
  push:
    branches: 
    - master

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build api docker image
      working-directory: ./api
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/gameshop-api:latest
    - name: Docker login
      run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gameshop-api:latest
  build-and-push-ui:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build ui docker image
      working-directory: ./ui
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/gameshop-ui:latest
    - name: Docker login
      run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gameshop-ui:latest
  build-and-push-db:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build db docker image
      working-directory: ./db
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/gameshop-db:latest
    - name: Docker login
      run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gameshop-db:latest
